backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "source/images/posts"
public_folder: "/images/posts"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "source/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: md
    fields: # The fields for each document, usually in front matter
      - {label: "Template", name: "template", widget: "hidden", default: "post.html"}
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Author (comma delimited, if more than one)", name: "author", width: "string"}
      - {label: "Hide from Site Search?", name: "hide", widget: "boolean", default: false}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Text Teaser", name: "teaserText", widget: "string"}
      - {label: "Image Teaser", name: "teaserImage", widget: "image"}
      - {label: "Keywords (comma delimited)", name: "keywords", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Main Class", name: "mainClass", widget: "hidden", default: "blog"}